language: groovy
sudo: false
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle"
script: "./travis-build.sh"
after_failure:
- "./travis/publish_reports.sh"
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: yjrvYcL2KStheccxqoc5qfL2lIplkzGmja7oc5ZyCELelYH6TxP2iCDSE2UvICymlrByAHk5rcoEqhH9vjkRYOQfgXWahT18RkppjFsgc3F0lD1ulhPhunYDaCi0xyyPMddVy8Y9wWbkAyl6MREGKVtKFpkFpJqM0uY+ieUuU1c=
  - secure: g03YHB4AwAMBuTz3L0LCh3pf51Wnnm/noL26ZmHaSvuDbGcZakwIfgclo/7cs16obQXZkbFyj9PqCSeXSHttLBca0cRW+1MU8qTIRhz7zHOzoOEFyxjNRW2Oi9zqpYULFoKNNY95c0JosPnRLdcRbVwmKm6XtqNc6zCGMJ+x79A=
  - secure: qwQDbAsXS01PdjtxFOyAn0y7epwLiowLKAvoyoU1Yutl/7zPZJxtqOVpEVjBc2qVCMKXBTR60tPtqH+mGjamB5GE5T4OYfxiPnpmXagp7eWCF/1swYrUKEUFDolEIM6aU6l6pui3wvmheHB0Mnk2i4DF0dNbWHps+NwhYgHXAfg=
  - secure: Fk7KukPKRQu9WI0NSvczhLAbgvabCI8d+cV8jbKhahScQMhSObTaxqk/Tb1JaI1vRQ3IHksGbsIGOMx2jK5hntpjF8MCY1e8Y4rVkPNWxDqbtKvzCbWKNOhR5lfalCjn5Plx/qdh0TbNbiYswY/idmAVkVOfP7Wy2CKoadsP9HE=
  - secure: DsItL1MTuV9GLC2JKblnFqTvj8swuM4C96sPHRjrz0OArs6QZ3oyuaYdWFQIQdgeaO08gvoyjjP5TrT5UWEO8j6ElAbQMoYISffcqSzmzo82rBQTrjNjWHQ98BOcM8ge1A8lInHEuOBnQVxpk4KB2SOPD2QJeUd1MC9qXZpWQig=
  - secure: 3dy+H77W9DUZnie/8VkkknD3v93+r5HWR6qxKim4C81EOk/FPFp64ejc9TIjoIs+24SKCfSCDRe3O9EqyJRH6UGFPFBsap59CTQALppM7nI9ws0JzW/JmLIuqRhT+INgoVnD3ZWZ9onHFgwHZEWmhcRYY/iMybKrxXgI0rFXy18=
  - secure: l7P4ZS1P2zl6fh1jQjOv28xl6uJUwxbcH7gorNly8kF5f14ebqH93uiGNctDHGHJ2a73iy632h8MG7btTdmP/s0t+Oz6ZZFyEUh4q6DVzOuOzJ6HEGn0u/uHdfgHACETwKqt8sQwmmYv4CV/EG9zgF8eIZGJMwrSCqtdHJTR5tI=
deploy:
  provider: releases
  api_key:
    secure: xRdXMWiKZt6IbMQC2PLjq+EYhNqHuxEMrBKrK7TG0h/C3gdAZP3oH/s//jVr6BqKtbmbPduQTWX5DAy1K2XlvtdEEh0t19JCQSTRMRBRw2LQKoq6sQz8iKD0kspfE4zbywxSLvitbuppj4SPcl55hEQ6PBF0MtWWvVlVZ0dygbk=
  file: build/libs/fields-${TRAVIS_TAG:1}.jar
  on:
    repo: grails-fields-plugin/grails-fields
    tags: true
