language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
- echo 'TESTING VARIABLES'
- echo "${TRAVIS_BRANCH:1}"
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Lari Hotari"
  - GIT_EMAIL="lari@hotari.net"
  - secure: h9Iujsq2khAd0WjqhF+9Hart01mA/E03K2w51lMr4i6aOXUvqF99npzlib/tG4NZlV8pocOKF7ICwx6r3vXc+D2xu4wfyGwPw0+RlwivZBaqeavMmFepVoUW3GBud7LFcmlCX8Br+YbDejXqFv8TgCJwG3X/fEqgRfdurSPwxr4=
  - secure: lDqlh/DbkXHjQkwIjK8MHyc7RIF8BAHaWsqAlc/NiIw/8saY33OYyqh3hnQWkjwdMrzLuy755P5mSZt35Cc54BXXh9hQNhbnQNGJbt85PmmbI7vhqiA0WUatRAb3ZvN52YMsQt/KvYCs3rLn7yJ3jmfGXoLhzVzrOB77XWsxagY=
  - secure: l0Ip7R//w4SjZY+rgLKG9xgF8v1+DE5oK2TxljdNM6IZ52D3XF9T4V/yjhRpU86ayb49a8HpL9HYk7a+Cm0zybSSBDlsw+OYrVMjqdEqPti4o2eERgARgW3CL57Lt5kizK7b4DqsMPWqKJrb/2VKK/wGx7sG7zYs/6EPb1dSSxo=
  - secure: o9Ko1d8BfkjK30bwAOl+d5lHu7I2REsPg49Z2jRvVCZQJdu5NSJnGWz/cDLgvMQAga32Yzbr6XM/bQSl5frka49RPrK7ahley4D45mZg0z5DXbgITjcIwxY7GgIHZwZ1GoNVw2JjXCbu/ufr4BfPxINuK9xwdzL9Z0ghGmmh674=
  - secure: heeNuZUfaktaurf7fRRW9YTnp47nPjwjzxQ/wFhqfk+BOJUHuXGqI3Mw9GBspE7zOlx5QgfuXbEndGW9gJUjPuKz5lSg4mCIvCMqvDo8pTx+UPNEXmz9VsAamIjACXDipXCngg0cLU651m8gtzsAGK/RCKwWQfgeZ/GuseuHqzo=
  - secure: g5FOiF4I+To6cJlMmqW2/DNlQ9bvC1t4SCHXUwNCH/uG4t9oBYP35Ubxb5xplsF6BmVSmIYwSB2NnWZYVxKGvq31Bqo1SnXMt/0Sv04+wS+Ey6Wy1PFIBH/p5j9a76n1z/6e5nHhBJU/T2QrqDfw85j7rFUfRAaELDtrc00FnYc=
deploy:
  provider: releases
  api_key:
    secure: gkZXTeAOejDU/RspONtcFmdqCNHz4w3O6LI7alHK5NpGMrdtvvamk3zrPhQArNk1KHpt8qUpMQYZd+JoZLAaURWdbwv/g0e+woKtbq4zFnRb8vspgXxvCt6u6G6p8gQaTPYfWT0q+bryBNQ6mEgt1PgTca1hB9lsmR3cU6vigdo=
  file: build/libs/fields-${TRAVIS_TAG:1}.jar
  on:
    repo: grails3-plugins/fields
